### ISSUE TITLE
Installation/Usage Help, Please

### ISSUE THREAD

**Issue by Grossdm** [jingyu9575/add-search-engine-from-mycroft-project#3]
I wasted time trying to install a search engine from [Mycroft Project](https://mycroftproject.com/) before learning that this capability had been removed from Firefox.

I was pleased to find your GitHub repo, but I don't see how to install or use your code.

Would you please provide some guidance?

Thank you,
Doug

**Comment by jingyu9575** [comment]
Here is the extension on Firefox Add-Ons:

https://addons.mozilla.org/firefox/addon/add-search-engine-from-mycroft/
