### ISSUE TITLE
No ellipsis in Firefox 89

### ISSUE THREAD

**Issue by xaviripo** [jingyu9575/add-search-engine-from-mycroft-project#6]
The "..." icon has disappeared in the latest redesign of Firefox, in version 89.0. See the attached picture of the Firefox location text box:

<img width="197" alt="The right side of the Firefox location text box, displaying two icons, none of which look like ellipsis." src="https://user-images.githubusercontent.com/14994483/121215713-89e83e00-c880-11eb-893e-b9fe17937458.png">

If it is relevant, I am using macOS Big Sur 11.2.3.

**Comment by jingyu9575** [comment]
1. Mycroft project has updated to include the workaround, so this extension is no longer needed.
2. On Firefox 89, instead of the "..." menu, please right-click the address bar.

![图片](https://user-images.githubusercontent.com/8923139/121546072-9bc31000-ca3d-11eb-99bf-55d9cf5f31ed.png)

**Comment by xaviripo** [comment]
Thanks you!
